### ISSUE TITLE
The problem when you are importing "dmstudio"

### ISSUE THREAD

**Issue by pomponchik** [seanhoran/dmstudio#2]
Hello! I couldn't to import this library.

```
>>> from dmstudio import dmcommands
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pomponchik/Desktop/Projects/locklib/venv/lib/python3.9/site-packages/dmstudio/__init__.py", line 10, in <module>
    import dmcommands
ModuleNotFoundError: No module named 'dmcommands'
>>> from dmstudio import dmfiles
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pomponchik/Desktop/Projects/locklib/venv/lib/python3.9/site-packages/dmstudio/__init__.py", line 10, in <module>
    import dmcommands
ModuleNotFoundError: No module named 'dmcommands'
>>> import dmstudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pomponchik/Desktop/Projects/locklib/venv/lib/python3.9/site-packages/dmstudio/__init__.py", line 10, in <module>
    import dmcommands
ModuleNotFoundError: No module named 'dmcommands'
```

**Comment by pomponchik** [comment]
(This module has been downloaded from the pip)

**Comment by pomponchik** [comment]
And... this is the same import command in the case of cloned from this repo library:

```
>>> from dmstudio import dmcommands
Traceback (most recent call last):
  File "/Users/pomponchik/Desktop/Projects/go_go/dmstudio/main.py", line 1, in <module>
    from dmstudio import dmcommands
  File "/Users/pomponchik/Desktop/Projects/go_go/dmstudio/dmstudio/__init__.py", line 5, in <module>
    import dmstudio.dmcommands
  File "/Users/pomponchik/Desktop/Projects/go_go/dmstudio/dmstudio/dmcommands.py", line 1, in <module>
    import dmstudio.initialize
  File "/Users/pomponchik/Desktop/Projects/go_go/dmstudio/dmstudio/initialize.py", line 1, in <module>
    import win32com.client
ModuleNotFoundError: No module named 'win32com'
```

My platform is macbook m1.

**Comment by Boudou92** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-ed6bee03714f> in <module>
----> 1 import dmstudio.dmcommands as dmcommands  # panggil package dmstudio

~\Anaconda64\lib\site-packages\dmstudio\__init__.py in <module>
      8 '''
      9 
---> 10 import dmcommands
     11 import dmfiles
     12 import special

ModuleNotFoundError: No module named 'dmcommands'

**Comment by seanhoran** [comment]
@Boudou92  @pomponchik Just download the files and paste them in your site packages directory. I don't thing the pip version will work. Also make sure you have the anaconda distribution installed. win32com comes by default
